version: '3.7'

services:

  api:
    container_name: lffs-api
    restart: always
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - shared-network

  client:
    container_name: lffs-client
    restart: always
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - shared-network

networks:
  shared-network: